version: "3"

services:
  app:
    container_name: receptori-frontend-container
    image: "noah071610/receptori-frontend:latest"
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      NODE_ENV: production
