name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "22.x"
      # - run: npm ci
      # - run: npm run test 테스트 도입 예정 (일단 백엔드만)

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        env:
          NEXT_PUBLIC_COOKIE_NAME: ${{secrets.NEXT_PUBLIC_COOKIE_NAME}}
          NEXT_PUBLIC_BUCKET_NAME: ${{secrets.NEXT_PUBLIC_BUCKET_NAME}}
          NEXT_PUBLIC_ADMIN_ID: ${{secrets.NEXT_PUBLIC_ADMIN_ID}}
          NEXT_PUBLIC_PORT: ${{secrets.NEXT_PUBLIC_PORT}}
          NEXT_PUBLIC_SERVER_PORT: ${{secrets.NEXT_PUBLIC_SERVER_PORT}}
          NEXT_PUBLIC_DOMAIN: ${{secrets.NEXT_PUBLIC_DOMAIN}}
          IMAGE_NAME: ${{secrets.IMAGE_NAME}}
          NEXT_PUBLIC_AMPLITUDE: ${{secrets.NEXT_PUBLIC_AMPLITUDE}}
        run: docker build --build-arg NEXT_PUBLIC_COOKIE_NAME=$NEXT_PUBLIC_COOKIE_NAME --build-arg NEXT_PUBLIC_BUCKET_NAME=$NEXT_PUBLIC_BUCKET_NAME --build-arg NEXT_PUBLIC_ADMIN_ID=$NEXT_PUBLIC_ADMIN_ID --build-arg NEXT_PUBLIC_PORT=$NEXT_PUBLIC_PORT --build-arg NEXT_PUBLIC_SERVER_PORT=$NEXT_PUBLIC_SERVER_PORT --build-arg NEXT_PUBLIC_DOMAIN=$NEXT_PUBLIC_DOMAIN --build-arg IMAGE_NAME=$IMAGE_NAME --build-arg NEXT_PUBLIC_AMPLITUDE=$NEXT_PUBLIC_AMPLITUDE -t receptori-frontend .

      - name: tagging
        run: docker tag receptori-frontend:latest noah071610/receptori-frontend:latest

      - name: Push to Dockerhub
        run: docker push noah071610/receptori-frontend:latest
