name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "22.x"
      # - run: npm ci
      # - run: npm run test 테스트 도입 예정 (일단 백엔드만)

      - name: Set .env for configuration
        run: |
          touch ./.env
          echo "NEXT_PUBLIC_COOKIE_NAME=${{ secrets.NEXT_PUBLIC_COOKIE_NAME }}" >> ./.env
          echo "NEXT_PUBLIC_BUCKET_NAME=${{ secrets.NEXT_PUBLIC_BUCKET_NAME }}" >> ./.env
          echo "NEXT_PUBLIC_ADMIN_ID=${{ secrets.NEXT_PUBLIC_ADMIN_ID }}" >> ./.env
          echo "NEXT_PUBLIC_PORT=${{ secrets.NEXT_PUBLIC_PORT }}" >> ./.env
          echo "NEXT_PUBLIC_SERVER_PORT=${{ secrets.NEXT_PUBLIC_SERVER_PORT }}" >> ./.env
          echo "NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN }}" >> ./.env
          echo "IMAGE_NAME=${{ secrets.IMAGE_NAME }}" >> ./.env
          echo "NEXT_PUBLIC_AMPLITUDE=${{ secrets.NEXT_PUBLIC_AMPLITUDE }}" >> ./.env
        shell: bash

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t receptori-client-env .

      - name: tagging
        run: docker tag receptori-client-env:latest noah071610/receptori-client-env:latest

      - name: Push to Dockerhub
        run: docker push noah071610/receptori-client-env:latest
