name: Docker ec2 CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: [self-hosted, label-go]

    steps:
      - name: Docker remove container
        run: |
          sudo docker stop receptori-client-env-container || true
          sudo docker rm receptori-client-env-container || true
          sudo docker rmi noah071610/receptori-client-env:latest || true

      - name: Docker pull
        run: |
          sudo docker pull noah071610/receptori-client-env:latest
          sudo docker run -d -p 3000:3000 --name receptori-client-env-container noah071610/receptori-client-env
