name: Docker ec2 CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: [self-hosted, label-go]

    steps:
      - name: Docker remove container
        run: |
          sudo docker compose down || true
          sudo docker rmi noah071610/receptori-frontend:latest || true

      - name: Docker pull
        run: |
          sudo docker pull noah071610/receptori-frontend:latest
          sudo docker compose up -d
