name: Docker ec2 CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: [self-hosted, label-go]

    steps:
      # - name: Set .env for configuration
      #   run: |
      #     touch ./.env
      #     echo "NEXT_PUBLIC_COOKIE_NAME=${{ secrets.NEXT_PUBLIC_COOKIE_NAME }}" >> ./.env
      #     echo "NEXT_PUBLIC_BUCKET_NAME=${{ secrets.NEXT_PUBLIC_BUCKET_NAME }}" >> ./.env
      #     echo "NEXT_PUBLIC_ADMIN_ID=${{ secrets.NEXT_PUBLIC_ADMIN_ID }}" >> ./.env
      #     echo "NEXT_PUBLIC_PORT=${{ secrets.NEXT_PUBLIC_PORT }}" >> ./.env
      #     echo "NEXT_PUBLIC_SERVER_PORT=${{ secrets.NEXT_PUBLIC_SERVER_PORT }}" >> ./.env
      #     echo "NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN }}" >> ./.env
      #     echo "IMAGE_NAME=${{ secrets.IMAGE_NAME }}" >> ./.env
      #     echo "NEXT_PUBLIC_AMPLITUDE=${{ secrets.NEXT_PUBLIC_AMPLITUDE }}" >> ./.env
      #   shell: bash

      - name: Docker remove container
        run: |
          sudo docker stop receptori-client-env-container || true
          sudo docker rm receptori-client-env-container || true
          sudo docker rmi noah071610/receptori-client-env:latest || true

      - name: Docker pull
        run: |
          sudo docker pull noah071610/receptori-client-env:latest
          sudo docker run -d -p 3000:3000 --name receptori-client-env-container noah071610/receptori-client-env
